// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPSAchievements
{
        public const string achievement_1000_times = "CgkI653j2KAEEAIQAg"; // <GPGSID>
        public const string achievement_100_times = "CgkI653j2KAEEAIQAQ"; // <GPGSID>
        public const string achievement_the_richest_man_on_the_planet = "CgkI653j2KAEEAIQCQ"; // <GPGSID>
        public const string achievement_overkill = "CgkI653j2KAEEAIQBA"; // <GPGSID>
        public const string achievement_oh_wow_okay = "CgkI653j2KAEEAIQBw"; // <GPGSID>
        public const string achievement_10000_times = "CgkI653j2KAEEAIQAw"; // <GPGSID>
        public const string achievement_iam_a_rich_now = "CgkI653j2KAEEAIQCA"; // <GPGSID>
        public const string achievement_rapid_fire = "CgkI653j2KAEEAIQBQ"; // <GPGSID>
        public const string achievement_monster = "CgkI653j2KAEEAIQBg"; // <GPGSID>
        public const string achievement_newkid_authenticated = "CgkI653j2KAEEAIQCg"; // <GPGSID>

}